### ISSUE TITLE
[event_collection] is a required string

### ISSUE THREAD

**Issue by gwtomlinson** [keenlabs/KeenClient-PHP#101]
Since upgrading to dev-master, getting this error:

Validation errors: [event_collection] is a required string: The name of the event collection you are analyzing.

I've tried this:
`$client->count('collection name here', ['timeframe' => 'this_14_days', 'group_by' => 'from']);`

and also this:
`$client->count(['event_collection' => 'collection name here', 'timeframe' => 'this_14_days', 'group_by' => 'from']);`

with exactly the same results.

Whilst the first one matches the documentation (string and array), it doesn't match the IDE hints in KeenIOClient.php (just an array):
`@method array count(array $args = array()) {@command KeenIO count}`

Any thoughts?

**Comment by josephwegner** [comment]
^ Fix is in that PR

**Comment by gwtomlinson** [comment]
This is all good, working again in master. Thanks!

**Comment by josephwegner** [comment]
DONESKI
