### ISSUE TITLE
New release based on Guzzle 6

### ISSUE THREAD

**Issue by stof** [keenlabs/KeenClient-PHP#107]
The dev version of this library has been updated to rely on Guzzle 6 rather than the old unmaintained Guzzle 3.
Is there any chance to tag a stable release including this work ?

**Comment by EmilyShepherd** [comment]
[v2.5.7](https://github.com/keenlabs/KeenClient-PHP/releases/tag/v2.5.7) uses Guzzle 6. :smile:

**Comment by stof** [comment]
why is it not mentioned in the changelog ?. But thanks anyway
