### ISSUE TITLE
PSR2 Standards

### ISSUE THREAD

**Issue by Sekonda** [keenlabs/KeenClient-PHP#116]
Hey, I noticed some of the package isn't fully compatible with PSR2 coding standards.

Would this be something worth considering for Hacktoberfest?

**Comment by tbarn** [comment]
Hey @Sekonda! Thanks for the issue! I'm down to consider it for Hacktoberfest. I was wondering, do you know of any negative consequences from this change in terms of usage of the SDK? I know PSR-2 has been out for a while now.

**Comment by tbarn** [comment]
Hey @Sekonda! Thanks for this issue! I'm down to consider for Hacktoberfest. I'll add the label now.

**Comment by arjank** [comment]
Shouldn't be too difficult. Working on it.

**Comment by tbarn** [comment]
Hey @arjank, @Sekonda already has a PR #117 opened for this issue. There might need to be some work done in the docs for it, but it is mostly complete.

**Comment by arjank** [comment]
I only saw your comment and the PR when I was about to commit my changes. I also made the test files PSR2 compliant (with only minor changes) and I'll commit and create a PR anyway.
