### ISSUE TITLE
PHP Client lacks error handling if request to Keen Service fails

### ISSUE THREAD

**Issue by jshim76** [keenlabs/KeenClient-PHP#67]
Currently, if access to the Keen API is blocked for some reason, then Guzzle throws the following error, which causes applications to fail without explicit error handling to check if the API endpoint is available:

"Uncaught Exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 35: Unknown SSL protocol error in connection to api.keen.io:443"

Would recommend either:
1)  Explicit recommendation in PHP SDK Docs to add error handling to catch connection errors OR
2)  Catch all exceptions which could possibly be thrown by Keen library or the vendor tools in library (such as Guzzle) to ensure there's no way the SDK could break other websites.

**Comment by jaketoolson** [comment]
Create a PR?

**Comment by stof** [comment]
Catching all exceptions would mean that debugging becomes really hard, as you don't get any info about failures.
and for any method meant to return something (any analysis method for instance), this would mean that it would use a special return value to indicate a failure (and then not knowing what the failure is), which makes the SDK actually harder to use.
So it is better to document that methods can throw exceptions and that you may want to catch them if they should not become failures in the website itself.

**Comment by elof** [comment]
Closing this one because it has been dormant for > a year. We are about to roll in an update, feel free to weigh back in if you think the topic is still relevant.
