### ISSUE TITLE
Low-performance with `curl_multi_select`

### ISSUE THREAD

**Issue by Rask** [keenlabs/KeenClient-PHP#68]
The Guzzle package uses `curl_multi_select` which is quite slow (blocks for x amount of seconds determined by a timeout).

Is there a surefire way to async this inside PHP script shutdown or can I implement my own cURL middleware for handling the HTTP request to KeenIO, essentially bypassing the `curl_multi_select` approach?

Currently our pageloads are 200% in case we need to send something to KeenIO using the client.

**Comment by josephwegner** [comment]
KeenIOClient is a child of [Guzzle's Client](http://docs.guzzlephp.org/en/latest/clients.html), so you should be able to configure it in the same way you would configure Guzzle.

You can override the default timeout used by `curl_multi_select` by [using an environment variable](http://docs.guzzlephp.org/en/latest/clients.html?highlight=timeout#environment-variables). Depending on your system, Guzzle still may wait for the full amount of the timeout (regardless of time for the requests to finish), but at least you can set that timeout lower.

You can actually [configure `cURL`](http://docs.guzzlephp.org/en/latest/faq.html#how-can-i-add-custom-curl-options) however you'd like, if there are other optimizations you want to make.

It also looks like Guzzle will let you [use a custom HTTP handler](http://guzzle.readthedocs.org/en/latest/handlers.html) - by default they use RingPHP which is cURL internally. You _could_ find a different handler, or use your own - it should work, but I don't think we've got anything documented regarding that.

**Comment by josephwegner** [comment]
@Rask I'm gonna close this - feel free to comment back if you are still having issues.
