### ISSUE TITLE
Absolute Timeframes are not encoded to JSON

### ISSUE THREAD

**Issue by josephwegner** [keenlabs/KeenClient-PHP#71]
My expectation is that if I want to use an absolute timeframe I would use some code like this:

```
$queryData=(array("api_key"=>KEEN_READ_KEY,
 "event_collection"=>KEEN_EVENT,"timeframe"=>["start"=>"2015-09-30T01:00:00-04:00",
 "end"=>'2015-09-30T01:59:59-04:00']));
```

However, this doesn't work. It passes a `timeframe['start']` parameter and `timeframe['end']` parameter to Keen, but the API actually expects a `timeframe` parameter that has a JSON encoded object with the start and end values.

I believe right now the work around is to just wrap the array in `json_encode`, but that is not ideal. The SDK should be able to do that encoding internally.

**Comment by stof** [comment]
From what I see, passing an array should work.

Can you post the code doing the SDK call too to see which method you are calling ?

**Comment by josephwegner** [comment]
I'm gonna close this. The fact that I'm the only person to report it probably means I'm just dumb.
