### ISSUE TITLE
How do you use addons?

### ISSUE THREAD

**Issue by cballou** [keenlabs/KeenClient-PHP#72]
Just wanted to know in the documentation how you would incorporate addons to your events. Thanks.

**Comment by hex337** [comment]
I think you can do it by just passing the values in as part of the event request like this:

```php
$event = ["purchase" => ["item" => "unicorn"], "keen" => ["addons" => ["name" => "keen:ip_to_geo", "input" => ["ip" => "ip_address"], "output" => "ip_info"]]]

$client->addEvent('purchases', $event);
```

**Comment by cballou** [comment]
:+1: 

I read the API docs more thoroughly and this is definitely correct.
