### ISSUE TITLE
Command was not found matching setDefaultOption

### ISSUE THREAD

**Issue by moazam1** [keenlabs/KeenClient-PHP#75]
We are having trouble setting up Keen.io php library in our wordpress project.

I have created a WordPress plugin which essentially sends user signup information to keen.io via ajax. I have checked keen library it works perfect for all scenarios but it fails when we use keen api in ajax.

Here is the error log:

    #0 /var/home/mysite/www/wp-content/plugins/event-tracking/public/vendor/keen-io/keen-io/src/Client/KeenIOClient.php(102): Guzzle\Service\Client->getCommand('setDefaultOptio...', Array)
	#1 /var/home/mysite/www/wp-content/plugins/event-tracking/public/vendor/keen-io/keen-io/src/Client/KeenIOClient.php(76): KeenIO\Client\KeenIOClient->__call('setDefaultOptio...', Array)
	#2 /var/home/mysite/www/wp-content/plugins/event-tracking/public/vendor/keen-io/keen-io/src/Client/KeenIOClient.php(76): KeenIO\Client\KeenIOClient->setDefaultOption('headers', Array)
	#3 /var/home/mysite/www/wp-content/plugins/event-tracking/public/class-event-tracking-public.php(44): KeenIO\Client\KeenIOClient::factory(Array)
	#4 /var/home/mysite/www/wp-content/plugins/event-tracking/public/class-event-tracking-public.php(139): Event_Tracking_Public->initiateClient()
	#5 [internal function]: Event_Tracking_Public->trackSignups('')
	#6 /var/home/mysite/www/wp-includes/plugin.php(525): call_user_func_array(Array, Array)
	#7 /var/home/mysite/www/wp-settings.php(413): do_action('wp_loaded')
	#8 /var/home/mysite/www/wp-config.php(104): require_once('/var/home/lucyk...')
	#9 /var/home/mysite/www/wp-load.php(37): require_once('/var/home/lucyk...')
	#10 /var/home/mysite/www/wp-blog-header.php(12): require_once('/var/home/lucyk...')
	#11 /var/home/mysite/www/index.php(17): require('/var/home/lucyk...')
	#12 {main}
	--------------------------
	#0 /var/home/mysite/www/wp-content/plugins/event-tracking/public/vendor/keen-io/keen-io/src/Client/KeenIOClient.php(102): Guzzle\Service\Client->getCommand('setDefaultOptio...', Array)
	#1 /var/home/mysite/www/wp-content/plugins/event-tracking/public/vendor/keen-io/keen-io/src/Client/KeenIOClient.php(76): KeenIO\Client\KeenIOClient->__call('setDefaultOptio...', Array)
	#2 /var/home/mysite/www/wp-content/plugins/event-tracking/public/vendor/keen-io/keen-io/src/Client/KeenIOClient.php(76): KeenIO\Client\KeenIOClient->setDefaultOption('headers', Array)
	#3 /var/home/mysite/www/wp-content/plugins/event-tracking/public/class-event-tracking-public.php(44): KeenIO\Client\KeenIOClient::factory(Array)
	#4 /var/home/mysite/www/wp-content/plugins/event-tracking/public/class-event-tracking-public.php(139): Event_Tracking_Public->initiateClient()
	#5 [internal function]: Event_Tracking_Public->trackSignups('')
	#6 /var/home/mysite/www/wp-includes/plugin.php(525): call_user_func_array(Array, Array)
	#7 /var/home/mysite/www/wp-settings.php(413): do_action('wp_loaded')
	#8 /var/home/mysite/www/wp-config.php(104): require_once('/var/home/lucyk...')
	#9 /var/home/mysite/www/wp-load.php(37): require_once('/var/home/lucyk...')
	#10 /var/home/mysite/www/wp-blog-header.php(12): require_once('/var/home/lucyk...')
	#11 /var/home/mysite/www/index.php(17): require('/var/home/lucyk...')
	#12 {main}
	--------------------------
	#0 /var/home/mysite/www/wp-content/plugins/event-tracking/public/vendor/keen-io/keen-io/src/Client/KeenIOClient.php(102): Guzzle\Service\Client->getCommand('setDefaultOptio...', Array)
	#1 /var/home/mysite/www/wp-content/plugins/event-tracking/public/vendor/keen-io/keen-io/src/Client/KeenIOClient.php(76): KeenIO\Client\KeenIOClient->__call('setDefaultOptio...', Array)
	#2 /var/home/mysite/www/wp-content/plugins/event-tracking/public/vendor/keen-io/keen-io/src/Client/KeenIOClient.php(76): KeenIO\Client\KeenIOClient->setDefaultOption('headers', Array)
	#3 /var/home/mysite/www/wp-content/plugins/event-tracking/public/class-event-tracking-public.php(44): KeenIO\Client\KeenIOClient::factory(Array)
	#4 /var/home/mysite/www/wp-content/plugins/event-tracking/public/class-event-tracking-public.php(139): Event_Tracking_Public->initiateClient()
	#5 [internal function]: Event_Tracking_Public->trackSignups('')
	#6 /var/home/mysite/www/wp-includes/plugin.php(525): call_user_func_array(Array, Array)
	#7 /var/home/mysite/www/wp-settings.php(413): do_action('wp_loaded')
	#8 /var/home/mysite/www/wp-config.php(104): require_once('/var/home/lucyk...')
	#9 /var/home/mysite/www/wp-load.php(37): require_once('/var/home/lucyk...')
	#10 /var/home/mysite/www/wp-admin/admin.php(31): require_once('/var/home/lucyk...')
	#11 {main}

I have already sent WordPress plugin and test.php file to your team.

**Comment by tbarn** [comment]
Hey @moazam1, can you confirm that it installed the older version of Guzzle? I know you might have specified installing an older version which is :+1: but it might have auto updated the version which would make sense that it couldn't find `setDefaultOption`.

**Comment by moazam1** [comment]
@tbarn I have newer version installed and it works fine in all scenarios except ajax requests.

**Comment by tbarn** [comment]
@moazam1 I found that SetDefaultOptions has been marked as deprecated in one of the newer versions of Guzzle. (Not sure which version it happened, had trouble finding that.) In this line here: https://github.com/keenlabs/KeenClient-PHP/blob/4461595a84e651f7d1a61f45e517161547be4db9/src/Client/KeenIOClient.php#L76 it is used. 

I haven't worked with the Keen PHP Client much, but I would make sure that your Guzzle version is not getting upgraded from any other packages you are using even if you have specified an older version in your composer.json. I would check the version it is running at runtime to make sure it matches the one that the Keen PHP Client is using.

**Comment by tbarn** [comment]
Related: Just a last thought before 2016, I will try and see how this client could be improved in 2016. Hopefully there's some low hanging fruit to improve the experience. 

I'm sorry about any frustration it has caused.

**Comment by kmfk** [comment]
@moazam1 - Have you modified the Keen PHP Client or Guzzle libraries at all after installing them? Can you show us the versions installed for `keen-io/keen-io` and `guzzle/guzzle` from your composer.lock file?  That may help in this case.

The call to to [`setDefaultOption()`](https://github.com/guzzle/guzzle/blob/v3.8.1/src/Guzzle/Http/Client.php) is falling into the magic `__call()` method on the Client because it can't be found or is inaccessible (private or protected). It's a weird thing to have happen with out modifying the Keen Client or Guzzle library after installing.

@tbarn - I've been watching [this PR](https://github.com/guzzle/command/pull/30) as the [guzzle/command](https://github.com/guzzle/command) and [guzzle/guzzle-services](https://github.com/guzzle/guzzle-services) libraries haven't made it to a stable v1 release since they were refactored for guzzle 5+. That PR is a big jump forward and once this stuff is resolved, it would be great to update the Keen PHP Client.

I believe, as discussed in a separate issue, an upgrade of the PHP Client may mean requiring PHP 5.4+.  PHP 5.5 comes installed on Ubuntu 14.04 LTS, but 12.04 defaults to 5.3 - and that may still be widely used.

**Comment by tbarn** [comment]
@kmfk, thanks for helping! It is super helpful to also know about the guzzle updates so I can be more informed for future work. 

@moazam1, did you have a chance to check out the suggestions?

**Comment by moazam1** [comment]
@tbarn Yes. 

I have not modified keen/guzzle. Guzzle version is: v3.9.3 and keen.io is ~2.5. I tried various things but none worked for me. Here is what I have done:

1. Upgraded composer and reinstalled all but nothing worked
2. Ran composer global update command
3. Ran composer dump command inside project directory

I am still getting same error on ajax requests only:

    .com/www/wp-content/plugins/event-tracking/public/vendor/keen-io/keen-io/src/Client/KeenIOClient.php(102): Guzzle\Service\Client->getCommand('setDefaultOptio...', Array)

I spent quite a lot time on this issue. I sent plugin for reproducing error but didn't get help from your team. I will use CURL for this project, my client does not want me to spend any more time on this issue.

**Comment by elof** [comment]
Apologies for the bad experience here @moazam1. We have building an officially supported WP plugin on our roadmap for the year. If you have any suggestions they would be welcomed, justin@keen.io or keen.chat and I'm @elof there. I'll be out on paternity for a bit, but will be back in full force very soon.
