### ISSUE TITLE
Please release a new version with the scope key bugfix

### ISSUE THREAD

**Issue by stof** [keenlabs/KeenClient-PHP#81]
Anyone using this library through Composer will receive only stable releases by default

**Comment by hex337** [comment]
Ah, yeah, sorry. I'll see if I can get that out today.

**Comment by stof** [comment]
Great thanks.

Btw, I haven't seen any announcement to tell that the format of master keys was changing, and so that any code dealing with scoped keys had to be updated. One of my coworker created his account used for local development recently, and faced issues saying that the key was too long. I finally understood the reason when looking at the changelog of the keen-js package (for which the maintainers pinged me on an issue I reported and fixed in it), where I discovered the fix for new keys.
Knowing that an update of the client was needed would have helped.

Is there a place where you announce such changes, which I have missed ?

**Comment by hex337** [comment]
Just pushed up a version 2.5.5 that should have the updated keys in there. As for the code change, we probably should have communicated it better. We didn't do a big announcement on this, just some documentation updates. In general, we're working on a better system to update our SDKs more proactively, but its harder for the ones we don't actively maintain (we maintain JS/Ruby/iOS/Java). Sorry for the confusion.

**Comment by stof** [comment]
> We didn't do a big announcement on this, just some documentation updates. In general, we're working on a better system to update our SDKs more proactively

Even if the SDK was updated on time, an announcement would still have let me know that I need to update it in my project (I'm not updating dependencies all the time). It would also have helped letting the community know that other SDKs were requiring some work.
Anyway, it is great to have a fix available.
