### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by manavo** [keenlabs/KeenClient-PHP#84]
If I get a chance I'll try and make a PR, but it would be good if a timeout could be added to the Guzzle client. At the moment there is no timeout, which causes issues in some cases!

**Comment by tbarn** [comment]
Hey @manavo! 

For your use case, is it helpful to use the Guzzle retry plugin? 

```
use KeenIO\Client\KeenIOClient;

$client = KeenIOClient::factory([
    'projectId' => $projectId,
    'writeKey'  => $writeKey,
    'readKey'   => $readKey
]);

// Use a static factory method to get a backoff plugin using the exponential backoff strategy
$backoffPlugin = BackoffPlugin::getExponentialBackoff();

// Add the backoff plugin to the client object
$client->addSubscriber($backoffPlugin);
```

**Comment by josephwegner** [comment]
Closing for now, as this should be available by tapping in to Guzzle directly. Thanks @tbarn
