### ISSUE TITLE
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

### ISSUE THREAD

**Issue by ctadlock** [keenlabs/KeenClient-PHP#86]

**Comment by caseysoftware** [comment]
Yes, but the library is currently dependent on a pair of plugins that have not been updated to more recent versions of Guzzle. I detailed that here:
https://github.com/keenlabs/KeenClient-PHP/issues/64#issuecomment-226047858

**Comment by ctadlock** [comment]
@caseysoftware Looks like there have been some updates.

**Comment by caseysoftware** [comment]
Yes, planning on tackling it. I've been busy the last couple weeks - 👶   😀

**Comment by nurettintopal** [comment]
Do you know that is there any release date to new version of this package(with Guzzle 6.x)? there are two issues about this topic, but all of them are too old.

**Comment by ctadlock** [comment]
@caseysoftware  Any updates? Its been over 6 months...

**Comment by josephwegner** [comment]
@ctadlock We will get to this soon.

I am closing all guzzle version related issues, and will create a new central issue to track the problem. We will get on the latest guzzle ASAP. I will link here from the new issue, for reference.
