### ISSUE TITLE
Add documentation for Data Enrichment

### ISSUE THREAD

**Issue by josephwegner** [keenlabs/KeenClient-PHP#91]
Data Enrichment is a super useful feature when sending events to Keen IO. You can see more about it here: https://keen.io/docs/streams/data-enrichment-overview/. 

The JavaScript docs in the API Reference is a good example: https://keen.io/docs/api/?javascript#data-enrichment

They would be good to include in the section about sending events to Keen.

**Comment by swapagarwal** [comment]
I'd like to take this up! 😄
