### ISSUE TITLE
Add documentation for caching a query

### ISSUE THREAD

**Issue by josephwegner** [keenlabs/KeenClient-PHP#92]
A cached query is a saved query with a `refresh_rate` set, you can see more about them here: https://keen.io/docs/api/#creating-a-cached-query

It would be useful to add documentation for how to create a cached query near the section about **Saved Queries**.

**Comment by dongido001** [comment]
Hey, is this issue still available?

**Comment by tbarn** [comment]
Hey @dongido001! Feel free to ping me instead. It is still available.

**Comment by dongido001** [comment]
@tbarn great!, what do I need to get started, I have tested the the endpoint locally with the sdk

**Comment by tbarn** [comment]
Great start!

You will need to write an example similar to what is in this [section](https://github.com/keenlabs/KeenClient-PHP#using-saved-queries) on how to create a Cached Query. You will also add it to that section. 

If you need a bit more help with the example, the [API reference](https://keen.io/docs/api/#creating-a-cached-query) might give you some ideas on what your example could be.

**Comment by dongido001** [comment]
Thanks @tbarn 

That should help. I'm on this!

**Comment by dongido001** [comment]
@tbarn [#126](https://github.com/keenlabs/KeenClient-PHP/pull/126)

**Comment by dongido001** [comment]
meanwhile @tbarn , on the doc  we have:

```The refresh rate value is in seconds, and must be more than 1 hour (3,600 seconds) and less than 24 hours (86,400 seconds).```

I tried using 3600, but it's not accepting it, I think the lowest time is 14400

**Comment by tbarn** [comment]
Looks like a typo, I'll get that fixed! Thanks for pointing it out.
