### ISSUE TITLE
Create release from master

### ISSUE THREAD

**Issue by gwtomlinson** [keenlabs/KeenClient-PHP#99]
Hi - can you please create a new release from master so we can get the latest guzzle update without having to rely on dev-master. Thanks.

**Comment by stof** [comment]
👍 for this. The dependency on the unmaintained guzzle library is painful, as it is incompatible with Symfony 3.

**Comment by gwtomlinson** [comment]
Actually, it's already updated from guzzle/guzzle to guzzlehttp/guzzle - you just need to use dev-master. My request is to have a release created from master :)

**Comment by stof** [comment]
@gwtomlinson I know that. But having to use dev versions is also painful, as composer does not allow them by default (and I don't have a direct dependency on it currently).
So my +1 is also for the release

**Comment by BernardoSilva** [comment]
+1 Since we want to restrict our code to a specific version.

Please make a new tag :)

**Comment by hetmansky** [comment]
+1 for this

**Comment by josephwegner** [comment]
Thanks for the feedback, y'all. We should be cutting a new version when #100 merges (prolly today).

**Comment by gwtomlinson** [comment]
Are we still waiting on this, @josephwegner ?

**Comment by BernardoSilva** [comment]
Can you create a new tag please? 🥇 

![image](https://cloud.githubusercontent.com/assets/1537510/23522722/06a9f852-ff7c-11e6-8e4b-4f8cb5d94b1d.png)

**Comment by simonstaton** [comment]
:shipit:

**Comment by EmilyShepherd** [comment]
A release would indeed be very useful, the idea of @gwtomlinson having to rely on `dev-master` for a project gives me the shivers :dash:

![Shivers](http://www.reactiongifs.com/wp-content/uploads/2013/06/marilyn-monroe-yuck-.gif)

**Comment by josephwegner** [comment]
lol, I'm the worst. New tag incoming.

**Comment by josephwegner** [comment]
Tada https://github.com/keenlabs/KeenClient-PHP/releases/tag/v2.5.7

**Comment by EmilyShepherd** [comment]
![Woop Woop](http://memecrunch.com/meme/1BXDF/woop-woop/image.jpg)

**Comment by hetmansky** [comment]
cool! Thanks
